apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloservice
  namespace: demo
spec:
  selector:
    matchLabels:
      app: helloservice
  template:
    metadata:
      labels:
        app: helloservice
    spec:
      terminationGracePeriodSeconds: 5
      containers:
      - name: server
        image: saiyam911/argocd-demo:sha-170ac5b
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
 name: helloservice-ingress
 namespace: demo
spec:
 rules:
 - host: hello.davonet.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: helloservice
            port:
              number: 80

