apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld-one  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helloworld-one
  template:
    metadata:
      labels:
        app: helloworld-one
    spec:
      containers:
      - name: helloworld-one
        image: mcr.microsoft.com/azuredocs/helloworld:v1
        ports:
        - containerPort: 80
        env:
        - name: TITLE
          value: "Ingress Demo 1"
---
apiVersion: v1
kind: Service
metadata:
  name: helloworld-one  
spec:
  type: ClusterIP
  ports:
  - port: 80
  selector:
    app: helloworld-one

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld-two  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helloworld-two
  template:
    metadata:
      labels:
        app: helloworld-two
    spec:
      containers:
      - name: helloworld-two
        image: mcr.microsoft.com/azuredocs/helloworld:v1
        ports:
        - containerPort: 80
        env:
        - name: TITLE
          value: "Ingress Demo 2"
---
apiVersion: v1
kind: Service
metadata:
  name: helloworld-two  
spec:
  type: ClusterIP
  ports:
  - port: 80
  selector:
    app: helloworld-two
---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hello-world-ingress
  annotations:
spec:
  ingressClassName: nginx
  rules:
  - host: one.davonet.com
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: helloworld-one
            port:
              number: 80
 
